# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

  desc "lane for android firebase app distribution"
  lane :distribute_with_firebase do
    sh "flutter build apk --release --build-name=1.0.0 --build-number=7 --no-tree-shake-icons"
    puts "Good job yara, you just build the apk ❤✨👸"
    gradle(
    task: 'assemble',
    build_type: 'Release'
    )
    puts "Woohoo, now yara you are starting distributing to firebase app distribution ❤✨👸"
    firebase_app_distribution(
    app: "1:556150346698:android:1ee75ea25e151fff467533",
    groups: "sprints_group",
    android_artifact_type: "APK",
    firebase_cli_token: "1//09FqWPBwbAYfSCgYIARAAGAkSNwF-L9IrHomolhHTqQcUWFi3znhBqXARMmQrnHtsRWi3FemeKQ-VPrFMHiv0KNcPzPgO-SuLxSE",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
    release_notes: "this is automated beta testing using fastlane... by yara;), i can change this each time i add a new release to firebase app distribution..., this my second time woohoo"
    )
    puts "Good job yara, Everything works fine ❤✨👸✔"
  end

end
